# Generated by Django 4.2.3 on 2023-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0002_notice_delete_users_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
